jobs:
  - script: >
      folder('testjobs')
  - script: >
    pipelineJob('testjobs/dockerexample') {
      definition {
         cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/nixuser/jenkinsfileexample')
                }
                branch('master')
              }
            scriptPath('Jenkinsfile')
            lightweight(true)
            }
        }
      }
}
